<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderFlow.Domain\OrderFlow.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Helper\Exception\" />
    <Folder Include="IPatterns\" />
    <Folder Include="IRepositories\" />
    <Folder Include="IServices\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
